# Generated by Django 5.2.8 on 2026-03-12 19:47

import django.utils.timezone
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('employee_number', models.CharField(blank=True, max_length=50, null=True)),
                ('google_sub', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('role', models.CharField(choices=[('client', 'Client'), ('employee', 'Employee')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users_customuser',
                'constraints': [models.UniqueConstraint(condition=models.Q(('employee_number__isnull', False), models.Q(('employee_number', ''), _negated=True)), fields=('employee_number',), name='uq_employee_number_not_null'), models.UniqueConstraint(condition=models.Q(('google_sub__isnull', False), models.Q(('google_sub', ''), _negated=True)), fields=('google_sub',), name='uq_google_sub_present'), models.CheckConstraint(condition=models.Q(models.Q(('employee_number__isnull', False), ('role', 'employee'), models.Q(('employee_number', ''), _negated=True)), models.Q(('role', 'employee'), _negated=True), _connector='OR'), name='ck_employee_has_number'), models.CheckConstraint(condition=models.Q(models.Q(('employee_number__isnull', True), ('role', 'client')), models.Q(('employee_number', ''), ('role', 'client')), ('role', 'client'), _connector='OR'), name='ck_client_no_emp_number')],
            },
            managers=[
                ('objects', users.models.CustomManager()),
            ],
        ),
    ]
