# Generated by Django 5.2.8 on 2026-03-29 04:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='employee_number',
            field=models.CharField(blank=True, help_text='Numeric employee identifier (employees only)', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Employee number must contain digits only.', regex='^\\d+$')]),
        ),
    ]
