# Generated by Django 5.2.8 on 2026-03-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_employee_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='google_sub',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
