# Generated by Django 5.2.8 on 2026-01-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_employee_number_customuser_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressid', models.AutoField(db_column='AddressId', primary_key=True, serialize=False)),
                ('street', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Street', max_length=120)),
                ('city', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='City', max_length=50)),
                ('province', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Province', max_length=10)),
                ('postalcode', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PostalCode', max_length=7)),
            ],
            options={
                'db_table': 'Address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('codename', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerid', models.AutoField(db_column='CustomerId', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='FirstName', max_length=20)),
                ('lastname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='LastName', max_length=20)),
                ('email', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Email', max_length=10)),
                ('phonenumber', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PhoneNumber', max_length=20)),
            ],
            options={
                'db_table': 'Customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customerservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('reqdate', models.DateField(db_column='reqDate')),
                ('redyear', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='redYear', max_length=4)),
                ('completed', models.BooleanField()),
            ],
            options={
                'db_table': 'CustomerService',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('object_repr', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS')),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('model', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS')),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeid', models.AutoField(db_column='EmployeeId', primary_key=True, serialize=False)),
                ('roleid', models.IntegerField(db_column='RoleId')),
                ('employeenumber', models.IntegerField(db_column='EmployeeNumber')),
                ('firstname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='FirstName', max_length=20)),
                ('lastname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='LastName', max_length=20)),
                ('phonenumber', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PhoneNumber', max_length=10)),
                ('staffstatus', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='StaffStatus', max_length=20)),
            ],
            options={
                'db_table': 'Employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KnoxAuthtoken',
            fields=[
                ('digest', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=128, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('token_key', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=25)),
            ],
            options={
                'db_table': 'knox_authtoken',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('serviceid', models.AutoField(db_column='ServiceId', primary_key=True, serialize=False)),
                ('servicetypeid', models.IntegerField(db_column='ServiceTypeId')),
                ('title', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Title', max_length=15)),
                ('description', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Description', max_length=50)),
                ('baseprice', models.DecimalField(db_column='BasePrice', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Service',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersCustomuser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200, null=True)),
                ('first_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('email', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200, unique=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('employee_number', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('role', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20)),
            ],
            options={
                'db_table': 'users_customuser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersCustomuserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'users_customuser_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersCustomuserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'users_customuser_user_permissions',
                'managed': False,
            },
        ),
    ]
