# Generated by Django 5.2.8 on 2026-02-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_address_delete_authgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('employee', 'Employee')], max_length=20),
        ),
    ]
