# Generated by Django 5.2.8 on 2026-02-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressid', models.AutoField(db_column='AddressId', primary_key=True, serialize=False)),
                ('street', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Street', max_length=120)),
                ('city', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='City', max_length=50)),
                ('province', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Province', max_length=10)),
                ('postalcode', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PostalCode', max_length=7)),
            ],
            options={
                'db_table': 'Address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerid', models.AutoField(db_column='CustomerId', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='FirstName', max_length=20)),
                ('lastname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='LastName', max_length=20)),
                ('email', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Email', max_length=10)),
                ('phonenumber', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PhoneNumber', max_length=20)),
            ],
            options={
                'db_table': 'Customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customerservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('reqdate', models.DateField(db_column='reqDate')),
                ('redyear', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='redYear', max_length=4)),
                ('completed', models.BooleanField()),
            ],
            options={
                'db_table': 'CustomerService',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeid', models.AutoField(db_column='EmployeeId', primary_key=True, serialize=False)),
                ('roleid', models.IntegerField(db_column='RoleId')),
                ('employeenumber', models.IntegerField(db_column='EmployeeNumber')),
                ('firstname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='FirstName', max_length=20)),
                ('lastname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='LastName', max_length=20)),
                ('phonenumber', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PhoneNumber', max_length=10)),
                ('staffstatus', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='StaffStatus', max_length=20)),
            ],
            options={
                'db_table': 'Employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('serviceid', models.AutoField(db_column='ServiceId', primary_key=True, serialize=False)),
                ('servicetypeid', models.IntegerField(db_column='ServiceTypeId')),
                ('title', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Title', max_length=15)),
                ('description', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Description', max_length=50)),
                ('baseprice', models.DecimalField(db_column='BasePrice', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Service',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Serviceimage',
            fields=[
                ('serviceimageid', models.AutoField(db_column='ServiceImageId', primary_key=True, serialize=False)),
                ('contenttype', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ContentType', max_length=100)),
                ('filename', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='FileName', max_length=50)),
                ('imagedata', models.BinaryField(db_column='ImageData', max_length='max')),
                ('createdat', models.DateTimeField(db_column='CreatedAt')),
            ],
            options={
                'db_table': 'ServiceImage',
                'managed': False,
            },
        ),
    ]
