# Generated by Django 5.2.8 on 2026-03-13 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressid', models.AutoField(db_column='AddressId', primary_key=True, serialize=False)),
                ('street', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Street', max_length=120)),
                ('city', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='City', max_length=50)),
                ('province', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Province', max_length=10)),
                ('postalcode', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PostalCode', max_length=7)),
            ],
            options={
                'db_table': 'Address',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bookingid', models.AutoField(db_column='BookingId', primary_key=True, serialize=False)),
                ('appointmenttime', models.DateTimeField(db_column='AppointmentTime')),
                ('status', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Status', max_length=15)),
            ],
            options={
                'db_table': 'Booking',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customerservice',
            fields=[
                ('customerserviceid', models.AutoField(db_column='CustomerServiceId', primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('reqdate', models.DateField(db_column='reqDate')),
                ('redyear', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='redYear', max_length=4)),
                ('completed', models.BooleanField()),
            ],
            options={
                'db_table': 'CustomerService',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeid', models.AutoField(db_column='EmployeeId', primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, db_column='FirstName', max_length=20, null=True)),
                ('lastname', models.CharField(blank=True, db_column='LastName', max_length=20, null=True)),
                ('phonenumber', models.CharField(blank=True, db_column='PhoneNumber', max_length=10, null=True)),
                ('staffstatus', models.CharField(blank=True, db_column='StaffStatus', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoiceid', models.AutoField(db_column='InvoiceId', primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True, db_column='Amount', null=True)),
                ('transactionref', models.IntegerField(blank=True, db_column='TransactionRef', null=True)),
                ('issuedate', models.DateTimeField(blank=True, db_column='IssueDate', null=True)),
            ],
            options={
                'db_table': 'Invoice',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('quotesid', models.AutoField(db_column='QuotesId', primary_key=True, serialize=False)),
                ('additionalserviceid', models.IntegerField(db_column='AdditionalServiceId')),
                ('taxamount', models.DecimalField(db_column='TaxAmount', decimal_places=2, max_digits=10)),
                ('totalamount', models.DecimalField(db_column='TotalAmount', decimal_places=2, max_digits=10)),
                ('currency', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Currency', max_length=3)),
                ('status', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Status', max_length=20)),
            ],
            options={
                'db_table': 'Quotes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('scheduleid', models.AutoField(db_column='ScheduleId', primary_key=True, serialize=False)),
                ('starttime', models.DateTimeField(db_column='StartTime')),
                ('endtime', models.DateTimeField(db_column='EndTime')),
                ('status', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Status', max_length=15)),
            ],
            options={
                'db_table': 'Schedule',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('serviceid', models.AutoField(db_column='ServiceId', primary_key=True, serialize=False)),
                ('title', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Title', max_length=15)),
                ('description', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Description', max_length=50)),
                ('baseprice', models.DecimalField(db_column='BasePrice', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Service',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(default='service-images', max_length=100)),
                ('storage_path', models.CharField(max_length=400)),
                ('content_type', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=100)),
                ('size_bytes', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ServiceImage',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Servicetype',
            fields=[
                ('servicetypeid', models.AutoField(db_column='ServiceTypeId', primary_key=True, serialize=False)),
                ('typecode', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TypeCode', max_length=10)),
                ('typename', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TypeName', max_length=10)),
            ],
            options={
                'db_table': 'ServiceType',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('siteid', models.AutoField(db_column='SiteId', primary_key=True, serialize=False)),
                ('mainlinesize', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MainLineSize', max_length=20)),
                ('doorcode', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DoorCode', max_length=15)),
                ('brandofheads', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='BrandOfHeads', max_length=30)),
                ('remarks', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Remarks', max_length=30)),
            ],
            options={
                'db_table': 'Site',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('userimageid', models.AutoField(primary_key=True, serialize=False)),
                ('bucket', models.CharField(default='profiles', max_length=100)),
                ('storage_path', models.CharField(max_length=512)),
                ('content_type', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=100)),
                ('size_byte', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users_userimage',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zoneid', models.AutoField(db_column='ZoneId', primary_key=True, serialize=False)),
                ('zonename', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ZoneName', max_length=15)),
                ('zonearea', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ZoneArea', max_length=20)),
                ('zonetype', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ZoneType', max_length=15)),
                ('baserate', models.DecimalField(db_column='BaseRate', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Zone',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerid', models.AutoField(db_column='CustomerId', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='FirstName', max_length=20)),
                ('lastname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='LastName', max_length=20)),
                ('phonenumber', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PhoneNumber', max_length=20)),
                ('addressid', models.ForeignKey(db_column='AddressId', on_delete=django.db.models.deletion.DO_NOTHING, to='core.address')),
            ],
            options={
                'db_table': 'Customer',
                'managed': True,
            },
        ),
    ]
