# Generated by Django 5.2.8 on 2026-03-05 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, db_column='UserId', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='customerid',
            field=models.ForeignKey(db_column='CustomerId', on_delete=django.db.models.deletion.DO_NOTHING, to='core.customer'),
        ),
        migrations.AddField(
            model_name='customerservice',
            name='customerid',
            field=models.ForeignKey(db_column='CustomerId', on_delete=django.db.models.deletion.DO_NOTHING, to='core.customer'),
        ),
        migrations.AddField(
            model_name='employee',
            name='addressid',
            field=models.OneToOneField(blank=True, db_column='AddressId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.address'),
        ),
        migrations.AddField(
            model_name='employee',
            name='roleid',
            field=models.ForeignKey(db_column='RoleId', on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, db_column='UserId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customerid',
            field=models.ForeignKey(blank=True, db_column='CustomerId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.customer'),
        ),
        migrations.AddField(
            model_name='quotes',
            name='customerid',
            field=models.ForeignKey(db_column='CustomerId', on_delete=django.db.models.deletion.DO_NOTHING, to='core.customer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='quoteid',
            field=models.ForeignKey(blank=True, db_column='QuoteId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.quotes'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='bookingid',
            field=models.ForeignKey(db_column='BookingId', on_delete=django.db.models.deletion.DO_NOTHING, to='core.booking'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='customerserviceid',
            field=models.ForeignKey(db_column='CustomerServiceId', on_delete=django.db.models.deletion.DO_NOTHING, to='core.customerservice'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='employeeid',
            field=models.ForeignKey(db_column='EmployeeId', on_delete=django.db.models.deletion.DO_NOTHING, to='core.employee'),
        ),
        migrations.AddField(
            model_name='quotes',
            name='serviceid',
            field=models.ForeignKey(db_column='ServiceId', on_delete=django.db.models.deletion.DO_NOTHING, to='core.service'),
        ),
        migrations.AddField(
            model_name='customerservice',
            name='serviceid',
            field=models.ForeignKey(db_column='ServiceId', on_delete=django.db.models.deletion.DO_NOTHING, to='core.service'),
        ),
        migrations.AddField(
            model_name='booking',
            name='serviceid',
            field=models.ForeignKey(db_column='ServiceId', on_delete=django.db.models.deletion.DO_NOTHING, to='core.service'),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='service',
            field=models.ForeignKey(db_column='ServiceId', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.service'),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='site',
            name='addressid',
            field=models.ForeignKey(db_column='AddressId', on_delete=django.db.models.deletion.DO_NOTHING, to='core.address'),
        ),
        migrations.AddField(
            model_name='site',
            name='customerid',
            field=models.ForeignKey(db_column='CustomerId', on_delete=django.db.models.deletion.DO_NOTHING, to='core.customer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='siteid',
            field=models.ForeignKey(db_column='SiteId', on_delete=django.db.models.deletion.DO_NOTHING, to='core.site'),
        ),
        migrations.AddField(
            model_name='zone',
            name='siteid',
            field=models.ForeignKey(db_column='SiteId', on_delete=django.db.models.deletion.DO_NOTHING, to='core.site'),
        ),
        migrations.AddField(
            model_name='quotes',
            name='zoneid',
            field=models.ForeignKey(db_column='ZoneId', on_delete=django.db.models.deletion.DO_NOTHING, to='core.zone'),
        ),
    ]
