# Generated by Django 5.2.8 on 2026-03-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_skip_token_blacklist_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='firstname',
            field=models.CharField(blank=True, db_column='FirstName', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lastname',
            field=models.CharField(blank=True, db_column='LastName', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phonenumber',
            field=models.CharField(blank=True, db_column='PhoneNumber', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='staffstatus',
            field=models.CharField(blank=True, db_column='StaffStatus', max_length=20, null=True),
        ),
    ]
