# Generated by Django 5.2.8 on 2026-02-10 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_groups_and_permissions'),
    ]

    operations = [
    ]
