# Generated by Django 5.2.8 on 2026-03-16 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='siteid',
            field=models.ForeignKey(blank=True, db_column='SiteId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.site'),
        ),
    ]
