# Generated by Django 5.2.8 on 2026-03-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_booking_siteid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Email', default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='phonenum',
            field=models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PhoneNum', default='', max_length=30),
            preserve_default=False,
        ),
    ]
