# Generated by Django 5.2.8 on 2026-02-10 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_drop_servicereport_table'),
    ]

    operations = [
    ]
