# Generated by Django 5.2.8 on 2026-03-08 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_employee_firstname_alter_employee_lastname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='servicetypeid',
        ),
        migrations.AddField(
            model_name='service',
            name='servicetype',
            field=models.ForeignKey(blank=True, db_column='ServiceTypeId', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.servicetype'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('servicetype', 'title'), name='uq_service_type_title'),
        ),
    ]
