# Generated by Django 5.2.8 on 2026-03-17 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_booking_email_booking_phonenum'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestQuote',
            fields=[
                ('requestquoteid', models.AutoField(db_column='RequestQuoteId', primary_key=True, serialize=False)),
                ('fullname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='FullName', max_length=50)),
                ('phonenumber', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PhoneNumber', max_length=20)),
                ('email', models.EmailField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Email', max_length=100)),
                ('street', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Street', max_length=100)),
                ('city', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='City', max_length=100)),
                ('province', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Province', max_length=50)),
                ('postalcode', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PostalCode', max_length=20)),
                ('producttype', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ProductType', max_length=100, null=True)),
                ('plumbing', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Plumbing', max_length=255, null=True)),
                ('zones', models.IntegerField(blank=True, db_column='Zones', null=True)),
                ('lighting', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Lighting', max_length=10, null=True)),
                ('system', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='System', max_length=10, null=True)),
                ('wifi', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='WiFi', max_length=10, null=True)),
                ('sensor', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Sensor', max_length=10, null=True)),
                ('status', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Status', default='pending', max_length=20)),
                ('customerid', models.ForeignKey(blank=True, db_column='CustomerId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.customer')),
            ],
            options={
                'db_table': 'RequestQuote',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ServiceLocation',
            fields=[
                ('servicelocationid', models.AutoField(db_column='ServiceLocationId', primary_key=True, serialize=False)),
                ('street', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Street', max_length=100, null=True)),
                ('city', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='City', max_length=100, null=True)),
                ('province', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Province', max_length=50, null=True)),
                ('postalcode', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PostalCode', max_length=20, null=True)),
                ('customerid', models.ForeignKey(blank=True, db_column='CustomerId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.customer')),
            ],
            options={
                'db_table': 'ServiceLocation',
                'managed': True,
            },
        ),
    ]
