# Generated by Django 5.2.11 on 2026-02-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_employee_user_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bookingid', models.AutoField(db_column='BookingId', primary_key=True, serialize=False)),
                ('appointmenttime', models.DateTimeField(db_column='AppointmentTime')),
                ('status', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Status', max_length=15)),
            ],
            options={
                'db_table': 'Booking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoiceid', models.AutoField(db_column='InvoiceId', primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True, db_column='Amount', null=True)),
                ('transactionref', models.IntegerField(blank=True, db_column='TransactionRef', null=True)),
                ('issuedate', models.DateTimeField(blank=True, db_column='IssueDate', null=True)),
            ],
            options={
                'db_table': 'Invoice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('quotesid', models.AutoField(db_column='QuotesId', primary_key=True, serialize=False)),
                ('additionalserviceid', models.IntegerField(db_column='AdditionalServiceId')),
                ('taxamount', models.DecimalField(db_column='TaxAmount', decimal_places=2, max_digits=10)),
                ('totalamount', models.DecimalField(db_column='TotalAmount', decimal_places=2, max_digits=10)),
                ('currency', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Currency', max_length=3)),
                ('status', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Status', max_length=20)),
            ],
            options={
                'db_table': 'Quotes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('roleid', models.AutoField(db_column='RoleId', primary_key=True, serialize=False)),
                ('rolename', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='RoleName', max_length=15)),
                ('description', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Description', max_length=30)),
                ('earnperhour', models.DecimalField(db_column='EarnPerHour', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('scheduleid', models.AutoField(db_column='ScheduleId', primary_key=True, serialize=False)),
                ('starttime', models.DateTimeField(db_column='StartTime')),
                ('endtime', models.DateTimeField(db_column='EndTime')),
                ('status', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Status', max_length=15)),
            ],
            options={
                'db_table': 'Schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicetype',
            fields=[
                ('servicetypeid', models.AutoField(db_column='ServiceTypeId', primary_key=True, serialize=False)),
                ('typecode', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TypeCode', max_length=10)),
                ('typename', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TypeName', max_length=10)),
            ],
            options={
                'db_table': 'ServiceType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('siteid', models.AutoField(db_column='SiteId', primary_key=True, serialize=False)),
                ('mainlinesize', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MainLineSize', max_length=20)),
                ('doorcode', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DoorCode', max_length=15)),
                ('brandofheads', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='BrandOfHeads', max_length=30)),
                ('remarks', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Remarks', max_length=30)),
            ],
            options={
                'db_table': 'Site',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zoneid', models.AutoField(db_column='ZoneId', primary_key=True, serialize=False)),
                ('zonename', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ZoneName', max_length=15)),
                ('zonearea', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ZoneArea', max_length=20)),
                ('zonetype', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ZoneType', max_length=15)),
                ('baserate', models.DecimalField(db_column='BaseRate', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Zone',
                'managed': False,
            },
        ),
    ]
