# Generated by Django 5.2.8 on 2026-02-13 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_booking_invoice_quotes_roles_schedule_servicetype_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
