# Generated by Django 5.2.8 on 2026-03-26 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_requestquote_servicelocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'managed': True, 'ordering': ['appointmenttime']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': True, 'ordering': ['customerid']},
        ),
        migrations.AlterModelOptions(
            name='customerservice',
            options={'managed': True, 'ordering': ['createdat']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'managed': True, 'ordering': ['employeeid']},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'managed': True, 'ordering': ['issuedate']},
        ),
        migrations.AlterModelOptions(
            name='quotes',
            options={'managed': True, 'ordering': ['quotesid']},
        ),
        migrations.AlterModelOptions(
            name='requestquote',
            options={'managed': True, 'ordering': ['requestquoteid']},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'managed': True, 'ordering': ['starttime', 'endtime']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'managed': True, 'ordering': ['serviceid']},
        ),
        migrations.AlterModelOptions(
            name='serviceimage',
            options={'managed': True, 'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='servicelocation',
            options={'managed': True, 'ordering': ['servicelocationid']},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'managed': True, 'ordering': ['servicetypeid']},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'managed': True, 'ordering': ['siteid']},
        ),
        migrations.AlterModelOptions(
            name='userimage',
            options={'managed': True, 'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'managed': True, 'ordering': ['zoneid']},
        ),
    ]
