# Generated by Django 5.2.8 on 2026-03-29 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_booking_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='roleid',
        ),
    ]
