# Generated by Django 5.2.8 on 2026-03-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_booking_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Email', max_length=100, null=True),
        ),
    ]
