# Generated by Django 5.2.8 on 2026-02-25 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceimage',
            options={'ordering': ['-id']},
        ),
    ]
