# Generated by Django 5.2.8 on 2026-02-25 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_serviceimage_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceimage',
            name='contenttype',
        ),
        migrations.RemoveField(
            model_name='serviceimage',
            name='createdat',
        ),
        migrations.RemoveField(
            model_name='serviceimage',
            name='imagedata',
        ),
        migrations.RemoveField(
            model_name='serviceimage',
            name='serviceimageid',
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='bucket',
            field=models.CharField(default='service-images', max_length=100),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.service'),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='size_bytes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='storage_path',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='filename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
