# Generated by Django 5.2.8 on 2026-04-02 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_budget_expense'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date']},
        ),
    ]
