# Generated by Django 5.2.8 on 2026-02-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_serviceimage_contenttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceimage',
            name='content_type',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='filename',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='storage_path',
            field=models.CharField(max_length=400),
            preserve_default=False,
        ),
    ]
