# Generated by Django 5.2.8 on 2026-04-02 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_budget_options_alter_expense_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerservice',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customerservice',
            name='createdat',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt'),
        ),
        migrations.CreateModel(
            name='LocationService',
            fields=[
                ('locationserviceid', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('customerserviceid', models.ForeignKey(db_column='CustomerServiceId', on_delete=django.db.models.deletion.CASCADE, related_name='location_services', to='core.customerservice')),
                ('servicelocationid', models.ForeignKey(db_column='ServiceLocationId', on_delete=django.db.models.deletion.CASCADE, related_name='location_services', to='core.servicelocation')),
            ],
            options={
                'db_table': 'LocationService',
                'managed': True,
                'unique_together': {('servicelocationid', 'customerserviceid')},
            },
        ),
    ]
