# Generated by Django 5.2.8 on 2026-03-03 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_serviceimage_content_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceimage',
            options={'managed': False},
        ),
    ]
