# Generated by Django 5.2.8 on 2026-04-06 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_employee_staffstatus_alter_employee_user'),
        ('core', '0011_alter_customerservice_completed_and_more'),
    ]

    operations = [
    ]
